spring:
  application:
    name: insurance-claims-and-wallet-service
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost